angular.module('auroraClass').config(function ($translateProvider) {
  $translateProvider.translations('en', {
    languages: {
      en: 'English',
      ar: 'العربية'
    },
    common: {
      applyToAll:'Apply to all pages',
      ok: 'OK',
      submit: 'Submit',
      emptyAssets: "No Records Were Found For This Search filters",
      cancel: 'Cancel',
      close: 'Close',
      noResults: 'No results',
      loadMore: 'Load more',
      typeToSearch: 'Type something to search by',
      preview: 'Preview',
      images: 'Images',
      uploadPhotoVideo: 'Upload Photo or Video',
      chooseFile: 'choose file',
      buttonUpload: 'Upload',
      search : 'Search for . . .',
      addQuestion: 'Add Selected Questions',
      warning:'Warning',
      no:'No',
      yes:'Yes',
      add:'add',
      delete:'delete',
      loading:'Loading...'
    },
    app: {
      name: 'Aurora'
    },
    sharing: {
      sharedWith : 'Shared with:',
      users : '{{count}} Students',
      groups : '{{count}} Groups'
    },
    subjects: {
      subject: 'Subject'
    },
    categories: {
      category: 'Category'
    },
    lessons: {
      images: {
        upload: "Upload",
        byURL: "Upload"
      },
      lessons: "Lessons",
      lessoneditor: "Lessons Editor",
      lesson: 'Lesson',
      anyTime:'Any Time',
      anyGrade:'Any Grade',
      anySubject:'Any Subject',
      anyGroup:'Any Group',
      anyOne:'AnyOne',
      anyType:'Any Type',
      finish:'Finish',
      no_lessons :'No lessons found',
      changesLosingConfirmation: 'Your changes will be lost. Are you sure you want to leave page?',
      linkTitle: 'Display text',
      linkURL: 'URL',
      addText: "Add Text",
      addNoteTitle: "Add New Note",
      noteTitle: "Note Title",
      addNote: "Add Note",
      addNewLink: 'Add new link',
      addLink: "Add Link",
      "background.theme" : "Theme",
      "background.color" : "Color",
      "background.backgroundTitle": "Set Slide Bakcground",
      "background.chooseTheme": "Choose Theme",
      "background.chooseColor": "Choose Color",
      "background.setBackground": "Set Background",
      search  : 'Search',
      subject : 'Subject : {{subject}}',
      group   : 'Group',
      grade   : 'Grade : {{grade}}',
      date    : 'Date',
      bySubject : 'By Subject',
      byGroup   : 'By Group',
      byGrade   : 'By Grade',
      byDate    : 'By Date',
      bystatus    : 'By Status',
      anystatus:'Any Status',
      byType    : 'By Type',
      createdBy: 'Created By',
      selectSubject : 'Select Subject',
      selectGroup   : 'Select Group',
      selectGrade   : 'Select Grade',
      selectDate    : 'Select Date',
      newLesson : 'Create New lesson',
      newlessonhdr : '',
      creationDate : 'Created at: ',
      sharing : 'Shared with:',
      student : 'Students',
      groups : 'Groups',
      assignmentReport : 'Assignment Report:',
      succeeded : 'Succeeded',
      residuum : 'Residuum',
      createlessontitle : 'Create Lesson',
      settings          : 'Lesson Settings',
      createlesson      : 'Lesson Details',
      assignment        : 'Assignment Report',
      publish           : 'Share Lesson',
      setup             : 'Lesson - Setup',
      setup_help        : '',
      photo             : 'Lesson Photo',
      name              : 'Create Lesson Name',
      summary           : 'Summary about lesson',
      startDate         : 'Start Date',
      endDate           : 'End Date',
      visibility        : 'Visibility',
      visExp            : 'How public you want this wall to be? Choose one',
      privat            : 'Private',
      privExp           : 'Only you and people you add by email can access this wall',
      pswdprtct         : 'Password Protected',
      pswdExp           : 'Visitors will be required to enter this password to access',
      canview           : 'Can View',
      hidden            : 'Hidden Link',
      hdnExp            : 'The wall will have a public link, but the link will be hidden from google and public areas of appenza',
      totalPub          : 'Totally Public',
      ttlpubExp         : 'The wall will be public.It can show up in google searches and be featured by appenza on the homepage',
      lessonStyle       : 'Lesson Style',
      StudentCan        : 'Student Can',
      nextStep          : 'Next Step',
      upload            : 'Upload',
      comment           : 'Comment',
      like              : 'Like',
      download          : 'Download',
      edit              : 'Update Lesson Details',
      open              : 'Open Lesson',
      delete            : 'Delete Lesson',
      share             : 'Share Lesson',
      classification    : 'Classification',
      publishHelp       : '',
      assignToGroups    : 'Assign to Groups &amp; Users',
      today    : 'Today',
      last_week: 'Last Week',
      last_month: 'Last Month',
      page: 'Page {{number}}',
      update: 'Update Lesson Settings',
      updateName: 'Update Lesson Name',
      sendUpdate: 'Update',
      newpage  : 'New Page',
      preview  : 'Preview',
      save     : 'Save',
      background : 'Background',
      username:'User Name : ',
      groupname :'Group Name : ',
      members :'Number of members : ',
      createdAt:'Created at {{date}}',
      color:'Color',
      clear:'Clear',
      browserSupport:'Your browser does not support HTML5 Canvas.',
      moveTo:'Move to',
      relatedResources:'Related Resources',
      addStickyNote:'Add New Sticky Note',
      title:'Title',
      required:'Required!',
      description:'Description : {{description}}',
      texteditor:'Text Editor',
      status:'Status : ',
      invalidDate:'Date is not Valid , should be after start date by an hour or more',
      invaledStartDate:'Date is not Valid , should be after current date ',
      subjectError:'please choose a subject.',
      gradeError:'please choose a grade.',
      stickyNoteError:' Title is required.',
      linktextError:'Display Text is required.',
      linkUrlError:'Url is required.',
      nameError:'Asssigment name is required',
      latest:'Latest Lessons'
    },
    navigation: {
      home: 'Home',
      quizzes: 'Quizzes',
      lessons: 'Lessons',
      calendar : 'CALENDAR',
      groups : 'Groups',
      dashboard : 'Dashboard',
      assignments: 'Assignments',
      settings: 'Settings',
      search : 'Search this site',
      homeRegister:'HOME',
      discoverRegister:'DISCOVER',
      aboutRegister:'ABOUT',
      supportRegister:'SUPPORT',
      login:'LOGIN',
      notifications : 'Notifications'
    },
    newlesson:{
      newpage  : 'New Page',
      background : 'Background'
    },
    quiz: {
      printDashboard:'Print',
      invalidDate:'Date is not Valid , should be after start date by an 10 minutes or more',
      attachmedia:'Attach Media',
      joinedGroups:'Joined Groups :',
      score:'Score',
      completed: 'Quiz Completed!',
      back:'Back',
      waitingassessment: 'Waiting Assessments',
      tocorrect:'To Correct',
      planned:'Planned',
      submit: 'Submitted',
      published: 'Published',
      closed :'Closed',
      view:'View',
      creator:'Creator',
      id:'Id',
      quesHeader:'Question Header',
      publishsearch:'Published',
      plann:'Planned',
      info: 'Quiz {{title}}, Total Score {{score}}',
      quizdetail:'Quizz detail',
      quzzies:'Quizzes',
      attachHeader:'Attach a file.',
      fillHeader:'Fill the empty spaces : ' ,
      essayHeader:'Write an essay :',
      matchHeader:'Match the next 2 lists :',
      mcqHeader:"Select the Right Answer : ",
      msqHeader:"Select All Right Answers : ",
      passageHeader:"Highlight in the next paragraph",
      sortHeader:"Sort the following list : ",
      trueHeader:" Check True or False: ",
      results:'Results',
      notShared:'Not Shared',
      search: 'Search',
      taken:'Taken',
      available:'Available',
      names:'Name',
      skip:'Skipped',
      partial:'Partial',
      type:'Type',
      pending:'Pending',
      correct:'Correct',
      success:'Success',
      fail:'Fail',
      submit:'Submit',
      inCorrect:'Incorrect',
      newQuiz:'Create New quiz',
      updatequiztitle: 'Update Quiz',
      truefalsetitle: 'True or False',
      labelimagetitle: 'Label image',
      questionstitle: 'Question Prompt',
      setAsCorrectAnswer: 'Set as correct answer',
      correctAnswer:'Correct Answer',
      attachments:'Attachments',
      selectVideo: 'Select video',
      selectAudio: 'Select audio',
      selectImage: 'Select image',
      selectanswer: 'Select answer',
      clearQuestion: "Clear Answers",
      question:'Question',
      save: 'Save',
      mcqTitle: 'MCQ',
      answers: 'Answers',
      addnewanswer: 'add new answer',
      removeAnswer: 'X Remove Answer',
      msqTitle: 'MSQ',
      blankstitle: 'Fill-in the blanks',
      blanksdesc: 'Use underline to specify where you would like a blank to appear in the text box',
      highlightTitle: 'Highlight',
      passageQuistionTitle: 'Write down the question',
      passageAnswerTitle: 'Select the correct answer',
      createquiztitle: 'Create Quiz',
      createquiz: 'Create Quiz',
      publish: 'Share',
      settings: 'Settings',
      setup: 'Setup & Privacy settings for quiz',
      setup_help: '',
      name: 'Create Quiz Name',
      updateName: 'Update Quiz Name',
      summary: 'Summary about quiz',
      startDate: 'Start Date',
      endDate: 'End Date',
      timelimit: 'Time Limit',
      resulttype: 'Result type',
      timeperquestion: 'Time per question',
      enablecomment: 'Enable Comments',
      enablecommentdetail: 'Allow student to see all correct anser at end of quiz',
      questionperpage: 'Question per page',
      questionperpagedetail: 'This option will be open without set time for question',
      period: 'Period',
      settingshelp: 'How public you want this wall to be? Choose one',
      randomise: 'Randomize Question',
      randomisedetail: 'Questions will be displayed in different order per student',
      setcorrectanswer: 'Show correct answer',
      hidePointValuesFromQuizDesc:'Final Score will be displayed to student upon submitting answers.',
      setcorrectanswerdetail: 'Allow student to see all correct answer at end of quiz',
      hidepointvaluesfromquiz: 'Show Final Score',
      changebackground: 'Change background image',
      addDropDwon: 'Add drop down',
      grade: 'Grade',
      subject: 'Subject',
      question: 'Question {{number}}',
      addToQuestionBank : 'Add to question bank',
      points : 'Question points',
      edit : 'Update Quiz Questions',
      open : 'Open Quiz',
      delete : 'Delete Quiz',
      share : 'Share Quiz',
      update: 'Update Quiz Settings',
      join: 'Take Quiz',
      bySubject : 'By Subject',
      byGroup   : 'By Group',
      byGrade   : 'By Grade',
      byDate    : 'By Date',
      byType    : 'By Type',
      createdBy: 'Created By',
      creationDate : 'Created at: {{date}}',
      newquizhdr : '',
      no_quizzes :'No Quizzes found',
      sharing : 'Shared with:',
      student : 'Students',
      groups : 'Groups',
      assignmentReport : 'Assignment Report:',
      succeeded : 'Succeeded',
      residuum : 'Residuum',
      viewers: "Viewers",
      quizzes: 'Quizzes',
      essaytitle:'Essay',
      finish:'Finish',
      bank:'Bank',
      preview:'Preview',
      byQuestionType: 'By Question Type',
      assignToGroups: 'Assign Quiz to Students',
      publishHelp : 'Share quiz With user groups or individuals',
      subject_name : 'Subject : {{subject}}',
      grade_name   : 'Grade : {{grade}}',
      setDropdownValues:'{{dropdownValues}}. Set dropdown values ',
      trueQuestion:'True',
      falseQuestion:'False',
      dashboardHeader:'Quizzes',
      editorAttach:'Attach',
      performanceSummary:'Performance Summmary',
      performanceSummaryMessg:'',
      performanceByQuestions:'Performance By Questions',
      performanceByQuestionsMessg:'',
      printResult:'Print Result',
      quizResult:'Quiz Result',
      congratulation:'Congratulations!',
      completedQuestions:'This quiz is finished you completed {{answered}} questions',
      totalQuestions:'Total questions: {{questions}}',
      toDoResults:'Waiting for Assessment',
      partialCorrect:"Partially Correct",
      correctResults:'Correct',
      incorrectResults:'Incorrect',
      totalResults:'Total Result',
      createdAt:'Created at: {{date}}',
      endPreview:'End Preview',
      minutesPreview:'{{time}} Minutes',
      previous:'Prev',
      today    : 'Today',
      last_week: 'Last Week',
      last_month: 'Last Month',
      studentAnswer:'Student Answer',
      evaluation:'Evaluation:  ',
      done:'Done',
      quizJoined:'Joined :',
      groupsShares:'{{groupsShares}} Group ',
      dashBoardShares: '{{groupsShares}} Group  {{studentShares}} Student',
      dashBoardgroup: 'Group {{groupname}} ',
      dashBoardgroupName: '{{groupname}} ',
      dashBoardduration: '{{duration}} day',
      posted:'Posted :',
      questionResult:'Question Result',
      periodDashboard:' Period :',
      quizReport:'Quiz Report : ',
      succeededDashboard:'{{succeeded}} Succeeded ',
      failedDashboard:'{{failed}} Failed ',
      take:'Take',
      takeQuiz:'Taking {{quizName}}',
      settingDashboard:'Settings',
      editDashboard:'Edit',
      publishDashboard:'Share',
      removeDashboard:'Remove',
      copyDashboard:'Copy',
      savedQuiz : 'Your work saved successfully',
      sortCorrection:' If student submitted incorrect answer, score will be zero. Else full mark.',
      highlightCorrection:'This type of questions will be manually graded by teacher',
      matchCorrection:'if student submitted correct/incorrect answers, score will be calculated according to ratio of correct answers.',
      negativeCorrection:'if student submitted incorrect answers, score will be decreased till zero is reached (negative grading).',
      latest:'Latest Quizzes',
      attachment :{
        title: "Attachment"
      },
      skipped : 'No Submissions',
      notTaken : 'Not Taken'
    },
    assignment: {
      print:'Print',
      copy:"Copy",
      completed: 'Assignment Completed!',
      waitingassessment: 'Waiting Assessments',
      tocorrect:'To Correct',
      planned:'Planned',
      submit: 'Submitted',
      published: 'Published',
      closed :'Closed',
      publishsearch:'Published',
      plann:'Planned',
      info: 'Assignment {{title}}, Total Score {{score}}',
      assignmentdetail:'Assignment detail',
      assignments:'Assignments',
      results:'Results',
      notShared:'Not Shared',
      search: 'Search',
      newAssignment:'Create new assignment',
      updateassignmenttitle: 'Update Assignment',
      truefalsetitle: 'True or False',
      sortTitle:'Sorting : ',
      matchtitle:'Matching',
      labelimagetitle: 'Label image',
      questionstitle: 'Question Prompt',
      setAsCorrectAnswer: 'Set as correct answer',
      correctAnswer:'Correct Answer',
      selectVideo: 'Select video',
      selectAudio: 'Select audio',
      selectImage: 'Select image',
      selectanswer: 'Select answer',
      save: 'Save',
      mcqTitle: 'MCQ',
      answers: 'Answers',
      addnewanswer: 'add new answer',
      removeAnswer: 'X Remove Answer',
      msqTitle: 'MSQ',
      blankstitle: 'Fill-in the blanks',
      blanksdesc: 'Use underline to specify where you would like a blank to appear in the text box',
      highlightTitle: 'Highlight',
      passageQuistionTitle: 'Write down the question',
      passageAnswerTitle: 'Use underline to specify where you would like a passage to appear',
      createassignmenttitle: 'Create Assignment',
      createassignment: 'Create Assignment',
      publish: 'Share',
      settings: 'Settings',
      setup: 'Setup & Privacy settings for assignment',
      setup_help: '',
      name: 'Create assignment Name',
      updateName: 'Update assignment Name',
      summary: 'Summary about assignment',
      startDate: 'Start Date',
      endDate: 'End Date',
      timelimit: 'Time Limit',
      resulttype: 'Result type',
      timeperquestion: 'Time per question',
      enablecomment: 'Enable Comments',
      enablecommentdetail: 'Allow student to see all correct anser at end of assignment',
      questionperpage: 'Question per page',
      questionperpagedetail: 'This option will be open without set time for question',
      period: 'Period',
      settingshelp: 'How public you want this wall to be? Choose one',
      randomise: 'Randomize Question',
      randomisedetail: 'Questions will be displayed in different order per student',
      setcorrectanswer: 'Show correct answer',
      setcorrectanswerdetail: 'Allow student to see all correct answer at end of assignment',
      hidepointvaluesfromassignment: 'Show Final Score',
      hidePointValuesFromQuizDesc:'Final Score will be displayed to student upon submitting answers.',
      changebackground: 'Change background image',
      addDropDwon: 'Add drop down',
      grade: 'Grade',
      subject: 'Subject',
      question: 'Question {{number}}',
      addToQuestionBank : 'Add to question bank',
      points : 'Question points',
      edit : 'Update assignment Questions',
      open : 'Open assignment',
      delete : 'Delete assignment',
      share : 'Share assignment',
      update: 'Update assignment Settings',
      join: 'Take assignment',
      bySubject : 'By Subject',
      byGroup   : 'By Group',
      byGrade   : 'By Grade',
      byDate    : 'By Date',
      byType    : 'By Type',
      createdBy: 'created by',
      creationDate : 'Created at: {{date}}',
      newassignmenthdr : '',
      no_assignments :'No assignments found',
      sharing : 'Shared with:',
      student : 'Students',
      groups : 'Groups',
      assignmentReport : 'Assignment Report:',
      succeeded : 'Succeeded',
      residuum : 'Residuum',
      viewers: "Viewers",
      essaytitle:'Essay',
      byQuestionType: 'By Question Type',
      assignToGroups: 'Assign assignment to Students',
      publishHelp : 'Share assignment with user groups or individuals',
      subject_name : 'Subject : {{subject}}',
      grade_name   : 'Grade : {{grade}}',
      setDropdownValues:'{{dropdownValues}}. Set dropdown values ',
      trueQuestion:'True',
      falseQuestion:'False',
      dashboardHeader:'Assignments',
      editorAttach:'Attach',
      performanceSummary:'Performance Summmary',
      performanceSummaryMessg:'',
      performanceByQuestions:'Performance By Questions',
      performanceByQuestionsMessg:'',
      printResult:'Print Result',
      assignmentResult:'Assignment Result',
      congratulation:'Congratulations!',
      completedQuestions:'This assignment is finished you completed {{answered}} questions',
      totalQuestions:'Total questions: {{questions}}',
      toDoResults:'Waiting for Assessment',
      partialCorrect:"Partially Correct",
      correctResults:'Correct',
      incorrectResults:'Incorrect',
      totalResults:'Total Result',
      createdAt:'Created at: {{date}}',
      endPreview:'End Preview',
      minutesPreview:'{{time}} Minutes',
      previous:'Prev',
      today    : 'Today',
      last_week: 'Last Week',
      last_month: 'Last Month',
      studentAnswer:'Student Answer',
      evaluation:'Evaluation:  ',
      done:'Done',
      assignmentJoined:'Joined :',
      groupsShares:'{{groupsShares}} Group ',
      dashBoardShares: '{{groupsShares}} Group  {{studentShares}} Student',
      dashBoardgroup: 'Group {{groupname}} ',
      dashBoardgroupName: '{{groupname}} ',
      dashBoardduration: '{{duration}} day',
      posted:'Posted :',
      periodDashboard:' Period :',
      succeededDashboard:'{{succeeded}} Succeeded ',
      failedDashboard:'{{failed}} Failed ',
      take:'Take',
      takeAssignment:'Taking {{assignmentName}}',
      settingDashboard:'Settings',
      editDashboard:'Edit',
      publishDashboard:'Share',
      removeDashboard:'Remove',
      latest:'Latest Assignments',

      no_assigments :'No Assigments found',
      skipped : 'No Submissions',
      notTaken : 'Not Taken'
    },
    users: {
      parent:'Parent',
      users: 'Users',
      login: 'Login',
      grade: 'Grade',
      class:'Class',
      school:'School',
      forgotPassword : 'Forgot Password',
      selectLanguage: 'Select Language',
      language: 'Language: ',
      roles: 'Role',
      selectRole: 'Select Role',
      register: 'Register',
      registration: '{{role}} Registration',
      already_registered: 'Have an account?',
      logout: 'Log out',
      welcome: 'Welcome {{name}}',
      has_account: "Don't have an account?",
      email: "Email",
      password: "Password",
      create : "Create an account",
      next :"Next",
      confirm : "Confirm password",
      phone : "Phone Number",
      last_name : "Last name",
      first_name : "First name",
      license : "Enter license key",
      licenseKey:'License key',
      settings: 'Settings',
      home: 'Home',
      name: 'Full name',
      save: 'Save',
      quizzes:'Quizzes',
      lessons:'Lessons',
      groups:'Groups',
      toDo:'To Do',
      news:'News',
      homeSlogan: 'Welcome to Aurora Educational Platform',
      homeCallToAction: 'Create account',
      homeCallToActionDescription: 'Join Aurora network with your license key, choose your account type and start activating your account',
      confirmPassError:'Passwords do not match',
      passError:'Password must be 8 digits or more',
      phoneError:'should be a mobile number ex:(01XXXXXXXXX)',
      licensekeyError :'Invalid License Key',
      changePassword:'Change Password',
      confirm:'Confirm'
    },
    groups: {
      addAll: 'Add all',
      byClass: 'By Class',
      classname: 'Class : ',
      username: 'Name : ',
      clearall: 'Clear All',
      advancedSearch: 'Advanced Search',
      addMembers: 'Add New Members',
      updateMembers: 'Update Group Members',
      name: 'Name',
      delete: 'Delete Group',
      update: 'Update',
      groups: 'Groups',
      findByName: 'Find groups by name',
      grade: 'Grade',
      category: 'Subject Area',
      subject: 'Subject',
      description: 'Group Description',
      resourceTitle: 'Resource Title',
      coverpic: 'Choose an image',
      selectGrade: 'Select Grade',
      selectCategory: 'Select Subject Area',
      selectSubject: 'Select Subject',
      setup: 'New Group',
      group: 'Group',
      open: 'Open Group',
      edit: 'Edit Group Members',
      updateSettings: 'Edit Group Settings',
      newGroup: 'Create New Group',
      no_groups: 'No Groups Exist',
      addMembersBtn: 'Add Members',
      today: 'Today',
      last_week: 'Last Week',
      last_month: 'Last Month',
      members: '{{count}} Members',
      create: 'Create',
      updateCover: 'update cover',
      updateStatus:'Update Status',
      createdAt: 'Created at {{date}}',
      addPhotoVideo:'Add Photo/Video',
      post:'Post'
    },
    comments: {
      save: 'Comment',
      edit: 'Edit',
      delete: 'Delete',
      writeComment: 'Write a comment...',
      comments:'Comments'
    },
    library: {
      library: 'Library',
      userAssets: 'There are {{count}} uploaded files.',
      items: '{{count}} Items',
      addToLibrary: 'Add to Library'
    },
    footer: {
      poweredBy:'Powered by',
      appenzaPhone:'+201 002 034 304',
      appenzaSupport:'support@appenza-studio.com',
      appenzaCopyright:'Copyright © 2015 LMS, Powered by appenza Studio',
      appenzaLink:'www.appenza-studio.com'
    }
  });
  $translateProvider.translations('ar', {
    languages: {
      en: 'English',
      ar: 'العربية'
    },
    comments: {
      save: 'حفظ',
      edit: 'تعديل',
      delete: 'حذف',
      writeComment: 'اكتب تعليق',
      comments:'تعليقات'
    },
    quiz: {
      invalidDate:'تاريخ غير مقبول يجب أن يكون بعد تاريخ البدء ب 10 دقائق أو أكثر',
      attachmedia:'أرفق ملف',
      joinedGroups:'المجموعات المنضمة :',
      score: 'الدرجة : ',
      completed: 'انتهى اﻻمتحان!',
      back: 'رجوع',
      waitingassessment: 'في انتظار التصحيح',
      tocorrect: 'للتصحيح',
      planned: 'مخطط',
      published: 'منشور',
      closed: 'مغلق',
      publishsearch: 'منشور',
      plann: 'مخطط',
      names:'اسم',
      skip:'لم يحل',
      success:'ناجح',
      fail:'راسب',
      submit:'إرسال',
      partial:'جزئي',
      taken:'محلول',
      available:'متاح',
      pending:'معلّق',
      correct:'صحيح',
      inCorrect:'غير صحيح',
      info: 'امتحان {{title}}, المجموع النهائي {{score}}',
      quizdetail: 'تفاصيل اﻻمتحان',
      quzzies: 'اﻻمتحانات',
      results: 'النتائج',
      notShared: 'غير مشاركة',
      attachHeader:'أرفق ملف.',
      fillHeader:'املأ الفراغات : ' ,
      essayHeader:'اكتب عن:',
      matchHeader:'صل بين المفردات التالية :',
      mcqHeader:"اختر الإجابة الصحيحة: ",
      msqHeader:"اختر الإجابات الصحيحة : ",
      passageHeader:"ظلل في النص التالي",
      sortHeader:"رتب العبارات التالية : ",
      trueHeader:" وضح مدى صحة العبارة: ",
      search: 'بحث',
      newQuiz: 'إنشاء امتحان',
      updatequiztitle: 'تعديل امتحان',
      truefalsetitle: 'صح ام خطأ',
      labelimagetitle: 'Label image',
      questionstitle: 'عنوان السؤال',
      setAsCorrectAnswer: 'هذه هي الإجابة الصحيحة',
      correctAnswer: 'إجابه صحيحة',
      attachments: 'مرفقات',
      selectVideo: 'اختر فيديو',
      selectAudio: 'اختر صوت',
      selectImage: 'اختر صوره',
      selectanswer: 'اختر إجابة',
      clearQuestion: "مسح الإجابات",
      question: 'سؤال',
      save: 'حفظ',
      mcqTitle: 'اختر الإجابة الصحيحة',
      answers: 'إجابات',
      addnewanswer: 'أضف إجابة جديدة',
      removeAnswer: 'X احذف إجابة',
      msqTitle: 'اختر الإجابات الصحيحة',
      blankstitle: 'املأ الفراغات',
      blanksdesc: 'ضع خطًا تحت الكلمة المراد إخفاؤها من النص',
      highlightTitle: 'ظلل',
      passageQuistionTitle: 'اكتب السؤال',
      passageAnswerTitle: 'اختر الإجابة الصحيحة',
      createquiztitle: 'إنشاء امتحان',
      createquiz: ' إنشاء امتحان',
      publish: 'مشاركة',
      settings: 'إعدادات',
      setup: 'إعداد اﻻمتحان',
      setup_help: '',
      name: 'الاسم',
      updateName: 'تعديل الاسم',
      summary: 'ملخص عن  اﻻمتحان',
      startDate: 'تاريخ البدء',
      endDate: 'تاريخ اﻻنتهاء',
      timelimit: 'الوقت',
      resulttype: 'نوع النتيجة',
      timeperquestion: 'الوقت لكل سؤال',
      enablecomment: 'إمكانية التعليق',
      enablecommentdetail: 'إمكانيه معرفه الإجابه الصحيحه عند الانتهاء من الحل',
      questionperpage: 'سؤال في كل صفحة',
      questionperpagedetail: 'هذه الخاصيه تكون متاحه في حالة عدم تحديد وقت للسؤال',
      period: 'فترة',
      settingshelp: 'How public you want this wall to be? Choose one',
      randomise: 'إعادة ترتيب الأسئلة',
      randomisedetail: 'ترتيب الأسئلة يختلف من طالب لآخر',
      setcorrectanswer: 'أظهر الإجابة الصحيحة',
      hidePointValuesFromQuizDesc: 'النتيجة النهائية ستعرض للطالب بمجرد اﻻنتهاء من حل الامتحان',
      setcorrectanswerdetail: 'اعرض الإجابات الصحيحة في نهاية اﻻمتحان',
      hidepointvaluesfromquiz: 'اعرض النتيجة النهائية',
      changebackground: 'تغيير صورة الخلفية',
      addDropDwon: 'Add drop down',
      grade: 'المرحلة الدراسية',
      subject: 'المادة',
      question: 'سؤال {{number}}',
      addToQuestionBank: 'أضف إلى بنك الأسئلة',
      points: 'درجات السؤال',
      edit: 'تعديل اسئلة اﻻمتحان',
      open: 'فتح اﻻمتحان',
      delete: 'حذف اﻻمتحان',
      share: 'مشاركة اﻻمتحان',
      update: 'تعديل إعدادات الامتحان',
      join: 'ابدأ اﻻمتحان',
      bySubject: 'حسب المادة',
      byGroup: 'حسب المجموعة',
      byGrade: 'حسب المرحلة الدراسية',
      byDate: 'حسب التاريخ',
      byType: 'حسب النوع',
      preview:'استعراض',
      bank:'بنك',
      finish:'انهاء',
      createdBy: ' أُنشئ بواسطة',
      creationDate: 'أُنشئ في: {{date}}',
      newquizhdr: '',
      no_quizzes: 'ﻻ يوجد امتحانات',
      sharing: 'مشارك مع:',
      student: 'طﻻب',
      groups: 'مجموعات',
      assignmentReport: 'نتيجة الواجب:',
      succeeded: 'ناجح',
      residuum: 'راسب',
      viewers: "عارضين",
      quizzes: 'امتحانات',
      essaytitle: 'مقال',
      byQuestionType: 'حسب نوع السؤال',
      assignToGroups: 'وجه امتحان للطﻻب',
      publishHelp: 'مشاركة الامتحان مع مجموعات او افراد',
      subject_name: 'مادة : {{subject}}',
      grade_name: 'مرحلة دراسية : {{grade}}',
      setDropdownValues: '{{dropdownValues}}. Set dropdown values ',
      trueQuestion: 'صح',
      falseQuestion: 'خطأ',
      dashboardHeader: 'امتحانات',
      editorAttach: 'أرفق',
      performanceSummary: 'توزيع الدرجات',
      performanceSummaryMessg: '',
      performanceByQuestions: 'الدرجة لكل سؤال',
      performanceByQuestionsMessg: '',
      printResult: 'اطبع النتائج',
      quizResult: 'نتيجة اﻻمتحان',
      congratulation: 'مبروك!',
      completedQuestions: 'انتهى الامتحان لقد قمت بحل {{answered}} أسئلة',
      totalQuestions: 'مجموع الأسئلة: {{questions}}',
      toDoResults: 'في انتظار التصحيح',
      partialCorrect: "صحيح جزئيا",
      correctResults: 'صحيح',
      incorrectResults: 'غير صحيح',
      totalResults: 'الدرجة النهائية',
      createdAt: 'أُنشئ في: {{date}}',
      endPreview: 'إنهاء العرض',
      minutesPreview: '{{time}} دقيقة',
      previous: 'السابق',
      today: 'اليوم',
      last_week: 'الأسبوع الماضي',
      last_month: 'الشهر الماضي',
      studentAnswer: 'إجابة الطلاب',
      evaluation: 'تقييم:  ',
      done: 'تم',
      quizJoined: 'مُنضَم :',
      groupsShares: '{{groupsShares}} مجموعة ',
      dashBoardShares: '{{groupsShares}} مجموعة  {{studentShares}} طالب',
      dashBoardgroup: 'مجموعة {{groupname}} ',
      dashBoardgroupName: '{{groupname}} ',
      dashBoardduration: '{{duration}} يوم',
      posted: 'نشر :',
      questionResult: 'نتيجة السؤال',
      periodDashboard: ' فترة :',
      quizReport: 'تقرير اﻻمتحان : ',
      succeededDashboard: '{{succeeded}} ناجح ',
      failedDashboard: '{{failed}} راسب ',
      take: 'ابدأ',
      takeQuiz: 'ابدأ {{quizName}}',
      settingDashboard: 'إعدادات',
      editDashboard: 'تعديل',
      publishDashboard: 'مشاركة',
      removeDashboard: 'حذف',
      savedQuiz: 'تم الحفظ بنجاح',
      sortCorrection: ' الإجابة الصحيحة = الدرجة الكاملة و الإجابة الخاطئة = صفر',
      highlightCorrection: 'هذا النوع من الاسئلة يتم تصحيحه بواسطة المدرس',
      matchCorrection: 'يحصل الطالب على نسبة الإجابات الصحيحة إلى الإجابات الكلية',
      negativeCorrection: 'اذا جاوب الطالب اجابات غير صحيحه سوف تقل الدرجه حتي تصل للصفر (تصحيح بالسالب).',
      latest:'الامتحانات الأحدث',
      view:'عرض',
      creator:'المؤلف',
      type:'نوع',
      id:'الرقم',
      quesHeader:'عنوان السؤال',
      attachment: {
        title: "مرفقات"
      },
      skipped: 'لم يتم الإرسال',
      notTaken: 'لم يتم الحل'
    },

    assignment: {
      completed: 'انتهى الواجب!',
      waitingassessment: 'في انتظار التصحيح',
      tocorrect:'للتصحيح',
      planned:'مخطط',
      submit: 'تم إرسالها',
      published: 'منشور',
      closed :'مغلق',
      publishsearch:'منشور',
      plann:'مخطط',
      info: 'الواجب {{title}}, المجموع النهائي {{score}}',
      assignmentdetail:'تفاصيل الواجب',
      assignments:'الواجبات',
      results:'النتائج',
      notShared:'غير مشاركة',
      search: 'بحث',
      newAssignment:'إنشاء واجب جديد',
      updateassignmenttitle: 'تعديل الواجب ',
      truefalsetitle: 'صح أم خطأ',
      sortTitle:'ترتيب : ',
      matchtitle:'توصيل',
      labelimagetitle: 'تعليق على الصورة',
      questionstitle: 'عنوان السؤال',
      setAsCorrectAnswer: 'هذه هي الإجابة الصحيحة',
      correctAnswer:' اجابة صحيحة',
      selectVideo: ' اختر فيديو',
      selectAudio: ' اختر صوت',
      selectImage: 'اختر صورة ',
      selectanswer: ' اختر إجابة',
      save: 'حفظ',
      mcqTitle: 'اختر الإجابة الصحيحة',
      answers: 'الإجابات',
      addnewanswer: 'أضف إجابة جديدة',
      removeAnswer: 'X احذف الإجابه',
      msqTitle: 'اختر الإجابات الصحيحة',
      blankstitle: 'املأ الفراغات',
      blanksdesc: 'ضع خطًا تحت الكلمة المراد إخفاؤها من النص',
      highlightTitle: 'ظلل',
      passageQuistionTitle: 'اكتب السؤال',
      passageAnswerTitle: 'اختر الإجابة الصحيحة',
      createassignmenttitle: 'إنشاء واجب جديد',
      createassignment: 'إنشاء واجب جديد',
      publish: 'مشاركة',
      settings: 'إعدادات',
      setup: 'إعداد الامتحان',
      setup_help: '',
      name: 'الاسم',
      updateName: '  عدل الاسم',
      summary: 'ملخص عن الواجب',
      startDate: 'تاريخ البدأ',
      endDate: 'تاريخ اﻻنتهاء ',
      timelimit: 'الوقت',
      resulttype: ' نوع النتيجة',
      timeperquestion: 'الوقت لكل سؤال',
      enablecomment: 'إمكانية التعليق',
      enablecommentdetail: 'السماح للطالب بمعرفة الإجابة الصحيحة في نهاية الامتحان',
      questionperpage: 'سؤال لكل صفحة',
      questionperpagedetail: 'This option will be open without set time for question',
      period: 'الفترة',
      settingshelp: 'رجاء اختيار درجة الخصوصية المطلوبة لهذه الشاشة',
      randomise: 'اعادة ترتيب الاسئلة',
      randomisedetail: 'اﻻسئلة ستعرض بترتيب مختلف لكل طالب',
      setcorrectanswer: 'اعرض اﻻجابة الصحيحة',
      setcorrectanswerdetail: 'السماح للطالب بمعرفه الإجابة الصحيحة في نهاية الواجب',
      hidepointvaluesfromassignment: 'عرض النتيجة النهائية',
      hidePointValuesFromQuizDesc:'النتيجة النهائية سوف تعرض للطالب عند الانتهاء من الامتحان.',
      changebackground: 'تغيير صورة الخلفية ',
      addDropDwon: 'أضف قائمة منبثقة',
      grade: 'مرحلة دراسية',
      subject: 'مادة',
      question: 'سؤال {{number}}',
      addToQuestionBank : 'أضف لبنك الأسئلة',
      points : 'درجات السؤال',
      edit : 'تعديل اسئلة الواجب',
      open : 'فتح الواجب',
      delete : 'حذف الواجب',
      share : 'مشاركة الواجب',
      update: 'تعديل إعدادات الواجب',
      join: 'بدأ ',
      bySubject : 'بالمادة',
      byGroup   : 'بالمجموعة',
      byGrade   : 'بالمرحلة الدراسية',
      byDate    : 'بالتاريخ',
      byType    : 'بالنوع',
      createdBy: ' أُنشئ بواسطة',
      creationDate : ' أُنشئ في: {{date}}',
      newassignmenthdr : '',
      no_assignments :'ﻻ يوجد واجبات',
      sharing : ' مشاركة مع:',
      student : 'طلاب',
      groups : 'مجموعات',
      assignmentReport : ' تقرير الواجب:',
      succeeded : 'تم بنجاح',
      residuum : 'راسب',
      viewers: "",
      essaytitle:'مقال',
      byQuestionType: 'بنوع السؤال',
      assignToGroups: 'تخصيص الواجب لطلاب',
      publishHelp : 'شارك الواجب مع مجموعة أو أفراد',
      subject_name : 'المادة : {{subject}}',
      grade_name   : 'المرحلة الدراسية : {{grade}}',
      setDropdownValues:'{{dropdownValues}}. Set dropdown values ',
      trueQuestion:'صح',
      falseQuestion:'خطأ',
      dashboardHeader:'واجبات',
      editorAttach:'أرفق',
      performanceSummary:'ملخص اﻻداء',
      performanceSummaryMessg:'',
      performanceByQuestions:'درجات كل سؤال',
      performanceByQuestionsMessg:'',
      printResult:'طباعة النتائج',
      assignmentResult:' نتيجة الواجب',
      congratulation:'مبروك!',
      completedQuestions:'الواجب انتهى ، لقد أجبت  {{answered}} أسئلة',
      totalQuestions:'مجموع اﻻسئلة: {{questions}}',
      toDoResults:'بانتظار التصحيح',
      partialCorrect:"صحيح جزئيا",
      correctResults:'صحيح',
      incorrectResults:'غير صحيح',
      totalResults:'المجموع النهائي',
      createdAt:'أُنشئ في: {{date}}',
      endPreview:'أنهِ العرض',
      minutesPreview:'{{time}} دقائق',
      previous:'السابق',
      today    : 'اليوم',
      last_week: 'آخر اسبوع',
      last_month: 'آخر شهر',
      studentAnswer:' اجابة الطالب',
      evaluation:'تقييم:  ',
      done:'تم',
      assignmentJoined:'انضم :',
      groupsShares:'{{groupsShares}} مجموعة ',
      dashBoardShares: '{{groupsShares}} مجموعة  {{studentShares}} طالب',
      dashBoardgroup: 'مجموعة {{groupname}} ',
      dashBoardgroupName: '{{groupname}} ',
      dashBoardduration: '{{duration}} يوم',
      posted:'نشر :',
      periodDashboard:' فترة :',
      succeededDashboard:'{{succeeded}} بنجاح ',
      failedDashboard:'{{failed}} فشل ',
      take:'ابدأ',
      takeAssignment:'ابدأ {{assignmentName}}',
      settingDashboard:'إعدادات',
      editDashboard:'تعديل',
      publishDashboard:'مشاركة',
      removeDashboard:'حذف',
      latest:'الواجبات اﻻخيرة',

      no_assigments :'ﻻ توجد واجبات',
      skipped : 'ﻻ توجد تقارير',
      notTaken : 'غير محلول'
    },
    lessons: {
      images: {
        upload: "تحميل",
        byURL: "تحميل"
      },
      lessons: "دروس",
      lessoneditor: "تعديل الدرس",
      lesson: 'درس',
      finish:'منتهية',
      anyTime:'كل اﻻوقات',
      anyGrade:'كل المراحل الدراسية',
      anySubject:' كل المواد',
      anyGroup:'كل المجموعات',
      anyOne:'أي شخص',
      anyType:'كل الأنواع',
      no_lessons :'ﻻ يوجد دروس ',
      changesLosingConfirmation: 'التغييرات التي قمت بها لم يتم حفظها , تأكيد الخروج؟',
      linkTitle: 'نص العرض',
      linkURL: 'عنوان URL',
      addText: "أضف نص",
      addNoteTitle: "أضف ملاحظة جديدة",
      noteTitle: "عنوان الملاحظة",
      addNote: "أضف ملاحظة",
      addNewLink: 'أضف رابط جديد',
      addLink: "أضف رابط",
      "background.theme" : "موضوع",
      "background.color" : "لون",
      "background.backgroundTitle": "اختر خلفية",
      "background.chooseTheme": "اختر موضوع",
      "background.chooseColor": "اختر لون",
      "background.setBackground": "اختر الخلفية",
      search  : 'بحث',
      subject : 'المادة : {{subject}}',
      group   : 'مجموعة',
      grade   : 'المرحلة الدراسية : {{grade}}',
      date    : 'التاريخ',
      bySubject : 'بالمادة',
      byGroup   : 'بالمجموعة',
      byGrade   : 'بالمرحلة الدراسية',
      byDate    : 'بالتاريخ',
      bystatus    : 'بالحالة',
      anystatus:'كل الحاﻻت',
      byType    : 'بالنوع',
      createdBy: 'أُنشئ بواسطة',
      selectSubject : 'اختر مادة',
      selectGroup   : 'اختر مجموعة',
      selectGrade   : 'اختر مرحلة دراسية',
      selectDate    : 'اختر تاريخ',
      newLesson : 'إنشاء درس جديد',
      newlessonhdr : '',
      creationDate : 'أُنشئ في: ',
      sharing : 'مشاركة مع:',
      student : 'طلاب',
      groups : 'مجموعات',
      assignmentReport : 'تقرير الواجب:',
      succeeded : 'تم بنجاح',
      residuum : 'راسب',
      createlessontitle : 'إنشاء درس',
      settings          : 'إعدادات الدرس',
      createlesson      : 'تفاصيل الدرس',
      assignment        : 'تقرير الواجب',
      publish           : 'مشاركة الدرس',
      setup             : 'إعداد الدرس',
      setup_help        : '',
      photo             : 'صورة الدرس',
      name              : 'اﻻسم',
      summary           : 'ملخص عن الدرس',
      startDate         : 'تاريخ البدء',
      endDate           : 'تاريخ اﻻنتهاء',
      visibility        : 'الرؤية',
      visExp            : 'رجاء اختيار درجة الخصوصية المطلوبة لهذه الشاشة',
      privat            : 'خاص',
      privExp           : 'أنت و اﻻشخاص الذين قمت باضافتهم بالبريد اﻻلكتروني بإمكانكم عرض هذه الصفحة',
      pswdprtct         : 'كلمة السر محمية',
      pswdExp           : 'سيكون مطلوبا من الزائرين استخدام كلمة السر هذه للدخول',
      canview           : 'إمكانية العرض',
      hidden            : 'إخفاء الرابط',
      hdnExp            : 'هذه الشاشة سيكون لها رابط متاح , لكن لن يظهر من خلال محركات البحث أو على المواقع العامة لـ Appenza',
      totalPub          : 'Totally Public',
      ttlpubExp         : 'هذه الشاشة ستكون متاحة للجميع . يمكن أن تظهر من خلال محركات البحث أو على الصفحة الرئيسية لموقع Appenza',
      lessonStyle       : 'نمط الدرس',
      StudentCan        : ' بإمكان الطالب',
      nextStep          : 'الخطوة التالية',
      upload            : 'Upload',
      comment           : 'تعليق',
      like              : 'إعجاب',
      download          : 'تحميل',
      edit              : 'تعديل تفاصيل الدرس',
      open              : 'فتح الدرس',
      delete            : 'حذف الدرس',
      share             : 'مشاركة الدرس',
      classification    : 'تصنيف',
      publishHelp       : '',
      assignToGroups    : 'تخصيص لأفراد و مجموعات',
      today    : 'اليوم',
      last_week: 'آخر أسبوع',
      last_month: 'آخر شهر',
      page: 'صفحة {{number}}',
      update: 'تعديل إعدادات الدرس',
      updateName: 'تعديل اسم الدرس',
      sendUpdate: 'تعديل',
      newpage  : 'صفحة جديدة',
      preview  : 'عرض',
      save     : 'حفظ',
      background : 'خلفية',
      username:'اسم المستخدم : ',
      groupname :'اسم المجموعة : ',
      members :'عدد الأعضاء : ',
      createdAt:'أُنشئ في {{date}}',
      color:'لون',
      clear:'حذف',
      browserSupport:'المتصفح الذي تستخدمه لا يدعم HTML5 Canvas.',
      moveTo:'انتقل الى',
      relatedResources:'مصادر ذات صلة',
      addStickyNote:'أضف بطاقة ملاحظة',
      title:'عنوان',
      required:'مطلوب!',
      description:'وصف : {{description}}',
      texteditor:'مدخل النصوص',
      status:'حالة : ',
      invalidDate:'تاريخ غير مقبول يجب أن يكون بعد تاريخ البدأ بساعة على الأقل',
      invaledStartDate:'تاريخ غير مقبول لا يمكنك اختيار تاريخ سابق ',
      subjectError:'اختر مادة',
      gradeError:'اختر مرحلة دراسية',
      stickyNoteError:' العنوان مطلوب',
      linktextError:'نص العرض مطلوب',
      linkUrlError:'عنوان Url مطلوب',
      nameError:'اﻻسم مطلوب',
      latest:'الدروس الأخيرة'
    },
    groups: {
      addAll: 'أضف الكل',
      byClass: 'بالفصل',
      classname: 'الفصل : ',
      username: 'الاسم : ',
      clearall: 'حذف الكل',
      advancedSearch: 'بحث متقدم',
      addMembers: 'أضف أعضاء جدد',
      updateMembers: 'تعديل أعضاء المجموعه',
      name: 'اسم',
      delete: 'حذف المجموعة',
      update: 'تعديل',
      groups: 'المجموعات',
      findByName: 'بحث عن مجموعة بالاسم',
      grade: 'المرحلة الدراسية',
      category: 'التخصص',
      subject: 'المادة الدراسية',
      description: 'وصف المجموعة',
      resourceTitle: 'العنوان',
      coverpic: 'اختر صورة',
      selectGrade: 'اختر المرحلة الدراسية',
      selectCategory: 'اختر التخصص',
      selectSubject: 'اختر المادة',
      setup: 'مجموعة جديدة',
      group: 'مجموعة',
      open: 'افتح المجموعة',
      edit: 'تعديل أعضاء المجموعة',
      updateSettings: 'تعديل إعدادات المجموعة',
      newGroup: 'إنشاء مجموعة جديدة',
      no_groups: 'ﻻ توجد مجموعات',
      addMembersBtn: 'أضف أعضاء',
      today: 'اليوم',
      last_week: 'آخر أسبوع',
      last_month: 'آخر شهر',
      members: '{{count}} اﻷعضاء',
      create: 'إنشاء',
      updateCover: 'تعديل الغلاف',
      updateStatus:'تعديل الحالة',
      createdAt: 'انشئ في {{date}}',
      addPhotoVideo:'أضف صورة / ﭬيديو',
      post:'نشر'
    },
    common: {
      ok: 'موافق',
      cancel: 'إلغاء',
      close: 'إغلاق',
      submit: 'تأكيد',
      emptyAssets: "ﻻ توجد نتائج للبحث",
      noResults: 'ﻻ نتائج',
      loadMore: 'المزيد',
      typeToSearch: 'اكتب للبحث',
      preview: 'استعرض',
      images: 'صور',
      uploadPhotoVideo: 'تحميل صورة أو فيديو',
      chooseFile: 'اختر ملف',
      buttonUpload: 'تحميل',
      search : 'بحث عن ....',
      addQuestion: 'أضف اﻷسئلة المختارة',
      warning:'تحذير',
      no:'لا',
      yes:'نعم',
      add:'أضف',
      delete:'حذف',
      loading:'جاري التحميل....'
    },
    users: {
      users: 'أعضاء',
      login: 'دخول',
      grade: 'المرحلة الدراسية',
      class:'الفصل',
      school:'المدرسة',
      forgotPassword : 'نسيت كلمة المرور',
      selectLanguage: 'اختر لغة',
      language: 'اللغة: ',
      roles: 'الدور',
      selectRole: 'اختر دور',
      register: 'تسجيل',
      registration: '{{role}} تسجيل',
      already_registered: 'مستخدم حالي ؟',
      logout: 'خروج',
      welcome: 'مرحبًا {{name}}',
      has_account: "ليس لديك حساب ؟",
      email: "البريد الإلكتروني",
      password: "كلمة السر",
      create : "إنشاء حساب",
      next :"التالي",
      confirm : " تأكيد كلمة السر",
      phone : " رقم الهاتف",
      last_name : "الاسم اﻷخير",
      first_name : " الاسم اﻷول",
      license : "أدخل رقم الترخيص",
      settings: 'إعدادات',
      home: 'الصفحة الرئيسية',
      name: 'الاسم بالكامل',
      save: 'حفظ',
      quizzes:'مسابقات',
      lessons:'دروس',
      groups:'مجموعات',
      toDo:'قائمة أعمال',
      news:'أخبار',
      homeSlogan: 'مرحبا بك في مجتمع أورورا التعليمي',
      homeCallToAction: 'إنشاء حساب',
      homeCallToActionDescription: 'انضم لشبكة أورورا باستخدام رقم الترخيص الخاص بك, اختر نوع الحساب الخاص بك ثم قم بتفعيل الحساب',
      confirmPassError:'كلمة السر غير متطابقة',
      passError:'كلمة السر يجب أن تتكون من 8 خانات أو أكتر',
      phoneError:'رجاء التأكد من إدخال رقم هاتف محمول بالصيغة التالية:(01XXXXXXXXX)',
      licensekeyError :'رقم ترخيص غير صحيح',
      changePassword:'تغيير كلمة السر',
      confirm:'تأكيد'
    },
    navigation: {
      home: 'الصفحة الرئيسية',
      quizzes: 'اﻻمتحانات',
      lessons: 'الدروس',
      calendar : 'النتيجه',
      groups : 'مجموعات',
      dashboard : 'Dashboard',
      assignments: 'واجبات',
      settings: 'إعدادات',
      search : 'بحث في الموقع',
      homeRegister:'الصفحة الرئيسية',
      discoverRegister:'DISCOVER',
      aboutRegister:'ABOUT',
      supportRegister:'دعم',
      login:'دخول',
      notifications : 'تنبيهات'
    },
    app: {
      name: 'أورورا'
    },
    //lessons: {
    //  images: {
    //    upload: "upoload"
    //  },
    //  search: 'بحث',
    //  lessons: 'الدروس',
    //  changesLosingConfirmation: 'لن يتم حفظ التغييرات. هل أنت متأكد أنك تريد المغادرة ؟',
    //  linkTitle: 'النص',
    //  linkURL: 'العنوان',
    //  addNewLink: 'إضافة رابط جديد',
    //  subject : 'المادة',
    //  byGroup   : 'المجموعات',
    //  grade   : 'المرحلة الدراسية',
    //  date    : 'التاريخ',
    //  newlesson : 'اضغط هنا لإضافة درس جديد',
    //  newlessonhdr : '',
    //  creationDate : 'تمت الإضافة في',
    //  sharing : 'مشارك مع:',
    //  student : 'ar-Students',
    //  group : 'ar-Groups',
    //  assignmentReport : 'ar-Assignment Report:',
    //  succeeded : 'تم بنجاح',
    //  residuum : 'ar-Residuum'
    //},
    toplinks: {
      quiz : 'مسابقات',
      lesson: 'دروس',
      calendar : 'نتيجة',
      mygroup : 'مجموعات',
      dashboard : 'ar-DASHBOARD',
      search : 'بحث في الموقع'
    },
    newlesson: {
      newpage  : 'صفحة جديدة',
      preview  : 'عرض',
      save     : 'حفظ',
      background : 'الخلفية'
    },

    createLesson:{
      createlessontitle : 'انشاء درس',
      settings          : 'إعدادات',
      createlesson      : 'إنشاء درس',
      assignment        : 'ar-Assignment Report',
      publish           : 'نشر',
      setup             : 'ar-Setup & Privacy settings for lesson',
      coverpic          : 'صورة الدرس',
      name              : 'الاسم',
      summary           : 'ملخص عن الدرس',
      strtDate          : 'ar-Start Date',
      endDate           : 'ar-End Date',
      visibility        : 'ar-Visibility',
      visExp            : 'ar-How public you want this wall to be? Choose one',
      privat            : 'ar-Private',
      privExp           : 'ar-Only you and people you add by email can access this wall',
      pswdprtct         : 'ar-Password Protected',
      pswdExp           : 'ar-Visitors will be required to enter this password to access',
      canview           : 'يمكن العرض',
      hidden            : 'ar-Hidden Link',
      hdnExp            : 'ar-The wall will have a public link, but the link will be hidden from google and public areas of appenza',
      totalPub          : 'ar-Totally Public',
      ttlpubExp         : 'ar-The wall will be public.It can show up in google searches and be featured by appenza on the homepage',
      lessonStyle       : 'ar-Lesson Style',
      StudentCan        : 'بإمكان الطالب',
      nextStep          : 'التالي',
      upload            : 'تحميل',
      comment           : 'تعليق',
      like              : 'إعجاب',
      download          : 'تحميل'
    },
    sharing: {
      sharedWith : ' مشاركة مع:',
      users : '{{count}} طﻻب',
      groups : '{{count}} مجموعات'
    },
    subjects: {
      subject: 'المادة'
    },
    categories: {
      category: 'تصنيف'
    },
    library: {
      library: 'Library',
      userAssets: 'There are {{count}} uploaded files.',
      items: '{{count}} Items',
      addToLibrary: 'Add to Library'
    }
  });
  $translateProvider.preferredLanguage('en');
  $translateProvider.useSanitizeValueStrategy('sanitizeParameters');
});

